# Generated by Django 5.2.4 on 2025-07-15 17:50

from django.db import migrations, models
from django.core.validators import MaxValueValidator, MinValueValidator

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Automovel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.TextField(max_length=10)),
                ('marca', models.TextField(max_length=100)),
                ('modelo', models.TextField(max_length=100)),
                ('ano', models.IntegerField(blank=False, null=False, validators=[MinValueValidator(1900), MaxValueValidator('year')])),
                ('cor', models.TextField(blank=True, max_length=50, null=True)),
                ('valor_diaria', models.DecimalField(decimal_places=2, max_digits=8)),
                ('disponivel', models.BooleanField(verbose_name=True)),
                ('data_cadastro', models.DateTimeField()),
            ],
        ),
    ]
